name: Bump version

on:
  pull_request:
    types: [opened]
    branches: [ "main" ]
    
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Up version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          git push
